'use client';
import { Bell, ExternalLink, LayoutDashboard, LogOut, Menu, Newspaper, PawPrint, Star, Users, X } from 'lucide-react';
import { usePathname } from 'next/navigation';
import { useCallback, useEffect, useState } from 'react';
const items = [{ href: '/dashboard', label: 'Dashboard', note: '管理トップ', icon: LayoutDashboard }, { href: '/cast', label: 'Cast / Staff', note: 'キャスト・スタッフ管理', icon: Users }, { href: '/news', label: 'News', note: 'お知らせ管理', icon: Newspaper }, { href: '/pickup', label: 'PICK UP', note: 'ピックアップ管理', icon: Star }];
export function AdminShell({ user, children }: { user: { displayName: string; email: string }; children: React.ReactNode }) {
  const pathname = usePathname(); const [open, setOpen] = useState(false);
  const prefetchRoute = useCallback((href: string) => {
    if (href.startsWith('/')) void fetch(href, { credentials: 'same-origin' }).catch(() => undefined);
  }, []);
  useEffect(() => {
    const warmup = window.setTimeout(() => {
      for (const item of items) if (item.href !== pathname) prefetchRoute(item.href);
    }, 500);
    return () => window.clearTimeout(warmup);
  }, [pathname, prefetchRoute]);
  const sidebar = <><div className="flex h-18 items-center gap-3 border-b border-slate-200 px-5"><span className="grid size-9 place-items-center rounded-xl bg-violet-600 text-white"><PawPrint size={19} /></span><div><p className="text-sm font-bold text-slate-900">BarMisaki</p><p className="text-[10px] font-semibold tracking-[.14em] text-slate-400">ADMIN CONSOLE</p></div></div><nav className="flex-1 space-y-1 p-3">{items.map(({ href, label, note, icon: Icon }) => { const active = pathname === href; return <a key={href} href={href} onClick={() => setOpen(false)} onPointerEnter={() => prefetchRoute(href)} onFocus={() => prefetchRoute(href)} className={`flex items-center gap-3 rounded-xl px-3 py-3 transition ${active ? 'bg-violet-50 text-violet-700' : 'text-slate-600 hover:bg-slate-50 hover:text-slate-900'}`}><Icon size={18} /><div><p className="text-sm font-semibold">{label}</p><p className="text-[10px] text-slate-400">{note}</p></div></a>; })}</nav><div className="space-y-1 border-t border-slate-200 p-3"><a href="https://barmisaki-official.yuuki-n-yugichu400.chatgpt.site" target="_blank" rel="noreferrer" className="flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-semibold text-slate-600 hover:bg-slate-50"><ExternalLink size={18} /> View Website</a><a href="/signout-with-chatgpt?return_to=/" target="_top" className="flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-semibold text-slate-500 hover:bg-rose-50 hover:text-rose-600"><LogOut size={18} /> Logout</a></div></>;
  return <div className="min-h-dvh bg-slate-50 text-slate-900"><aside className="fixed inset-y-0 left-0 z-40 hidden w-64 flex-col border-r border-slate-200 bg-white lg:flex">{sidebar}</aside>{open && <div className="fixed inset-0 z-50 lg:hidden"><button className="absolute inset-0 bg-slate-950/25" onClick={() => setOpen(false)} aria-label="メニューを閉じる" /><aside className="relative flex h-full w-72 flex-col bg-white shadow-xl">{sidebar}<button className="absolute right-3 top-3 grid size-9 place-items-center rounded-lg hover:bg-slate-100" onClick={() => setOpen(false)}><X /></button></aside></div>}<div className="lg:pl-64"><header className="sticky top-0 z-30 flex h-18 items-center justify-between border-b border-slate-200 bg-white/90 px-4 backdrop-blur sm:px-7"><div className="flex items-center gap-3"><button onClick={() => setOpen(true)} className="grid size-10 place-items-center rounded-xl border border-slate-200 lg:hidden" aria-label="メニューを開く"><Menu /></button><div><p className="text-sm font-semibold">{user.displayName}</p><p className="hidden text-xs text-slate-400 sm:block">{user.email}</p></div></div><button className="relative grid size-10 place-items-center rounded-xl border border-slate-200 text-slate-500"><Bell size={18} /><span className="absolute right-2 top-2 size-1.5 rounded-full bg-violet-600" /></button></header><div className="p-4 sm:p-7 lg:p-9">{children}</div></div></div>;
}
