'use client';

import { Eye, EyeOff, ImageIcon, Pencil, Plus, Trash2 } from 'lucide-react';
import { useState } from 'react';
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from '@/components/ui/alert-dialog';
import { FormModal, ImageUpload, LoadingState, mutateAdmin, NewsRecord, PageHeading, Toast, useAdminData } from '@/components/admin-common';

const empty: Omit<NewsRecord, 'id'> = { title: '', date: new Date().toISOString().slice(0, 10), thumbnailUrl: '', content: '', published: true };
export function NewsManager() {
  const { data, error, reload } = useAdminData(); const [editing, setEditing] = useState<NewsRecord | 'new' | null>(null); const [form, setForm] = useState(empty); const [confirmSave, setConfirmSave] = useState(false); const [deleting, setDeleting] = useState<NewsRecord | null>(null); const [toast, setToast] = useState<{ text: string; kind: 'success' | 'error' } | null>(null); const [busy, setBusy] = useState(false);
  const openNew = () => { setForm(empty); setEditing('new'); }; const openEdit = (item: NewsRecord) => { setForm({ title: item.title, date: item.date, thumbnailUrl: item.thumbnailUrl, content: item.content, published: item.published }); setEditing(item); };
  const update = (key: keyof typeof form, value: string | boolean) => setForm((current) => ({ ...current, [key]: value }));
  const save = async () => { setBusy(true); try { const result = await mutateAdmin(editing === 'new' ? { action: 'news:create', data: form } : { action: 'news:update', id: editing?.id, data: form }); setToast({ text: result.message || '保存しました。', kind: 'success' }); setEditing(null); await reload(); } catch (e) { setToast({ text: e instanceof Error ? e.message : '保存に失敗しました。', kind: 'error' }); } finally { setBusy(false); setConfirmSave(false); } };
  const remove = async () => { if (!deleting) return; setBusy(true); try { const result = await mutateAdmin({ action: 'news:delete', id: deleting.id }); setToast({ text: result.message || '削除しました。', kind: 'success' }); setDeleting(null); await reload(); } catch (e) { setToast({ text: e instanceof Error ? e.message : '削除に失敗しました。', kind: 'error' }); } finally { setBusy(false); } };
  return <main><PageHeading eyebrow="News" title="お知らせ管理" note="お知らせの作成・編集・公開状態を管理します。" action={<button onClick={openNew} className="inline-flex h-11 items-center justify-center gap-2 rounded-xl bg-violet-600 px-4 text-sm font-bold text-white hover:bg-violet-700"><Plus size={17} /> 新しいお知らせ</button>} />
    {!data ? <LoadingState /> : <div className="admin-card mt-8 overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[820px] text-left"><thead className="border-b border-slate-200 bg-slate-50 text-xs text-slate-500"><tr><th className="px-5 py-4 font-semibold">お知らせ</th><th className="px-4 py-4 font-semibold">投稿日</th><th className="px-4 py-4 font-semibold">公開状態</th><th className="px-5 py-4 text-right font-semibold">操作</th></tr></thead><tbody className="divide-y divide-slate-100">{data.news.map((item) => <tr key={item.id} className="hover:bg-slate-50/70"><td className="px-5 py-4"><div className="flex items-center gap-3"><div className="grid size-14 place-items-center overflow-hidden rounded-xl bg-slate-100">{item.thumbnailUrl ? <img src={item.thumbnailUrl} alt="" className="h-full w-full object-cover" /> : <ImageIcon size={18} className="text-slate-400" />}</div><div><p className="font-semibold">{item.title}</p><p className="mt-1 max-w-md truncate text-xs text-slate-400">{item.content || '本文未登録'}</p></div></div></td><td className="px-4 py-4 text-sm text-slate-600">{item.date}</td><td className="px-4 py-4">{item.published ? <span className="inline-flex items-center gap-1 rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-bold text-emerald-700"><Eye size={12} /> 公開</span> : <span className="inline-flex items-center gap-1 rounded-full bg-slate-100 px-2.5 py-1 text-xs font-bold text-slate-500"><EyeOff size={12} /> 非公開</span>}</td><td className="px-5 py-4"><div className="flex justify-end gap-2"><button onClick={() => openEdit(item)} className="inline-flex items-center gap-1 rounded-lg border border-slate-200 px-3 py-2 text-xs font-semibold text-slate-600 hover:bg-slate-50"><Pencil size={14} /> 編集</button><button onClick={() => setDeleting(item)} className="inline-flex items-center gap-1 rounded-lg border border-rose-200 px-3 py-2 text-xs font-semibold text-rose-600 hover:bg-rose-50"><Trash2 size={14} /> 削除</button></div></td></tr>)}</tbody></table></div></div>}
    {error && <p className="mt-4 text-sm text-rose-600">{error}</p>}
    {editing && <FormModal title={editing === 'new' ? '新しいお知らせ' : 'お知らせを編集'} onClose={() => setEditing(null)}><form onSubmit={(e) => { e.preventDefault(); setConfirmSave(true); }} className="space-y-6 p-5 sm:p-7"><ImageUpload value={form.thumbnailUrl} onChange={(url) => update('thumbnailUrl', url)} label="サムネイル画像" /><div className="grid gap-5 sm:grid-cols-[1fr_180px]"><label><span className="field-label">タイトル *</span><input className="admin-input" required value={form.title} onChange={(e) => update('title', e.target.value)} /></label><label><span className="field-label">投稿日 *</span><input className="admin-input" type="date" required value={form.date} onChange={(e) => update('date', e.target.value)} /></label></div><label><span className="field-label">本文</span><textarea className="admin-input min-h-64 resize-y leading-7" value={form.content} onChange={(e) => update('content', e.target.value)} placeholder="お知らせ本文を入力してください。改行はそのまま反映されます。" /></label><label className="flex cursor-pointer items-center gap-3 rounded-xl border border-slate-200 p-4"><input type="checkbox" className="size-4 accent-violet-600" checked={form.published} onChange={(e) => update('published', e.target.checked)} /><div><p className="text-sm font-bold">公開する</p><p className="mt-0.5 text-xs text-slate-400">ONにすると公式サイトのお知らせ一覧へ表示されます。</p></div></label><div className="flex justify-end gap-3 border-t border-slate-200 pt-5"><button type="button" onClick={() => setEditing(null)} className="rounded-xl border border-slate-300 px-5 py-3 text-sm font-semibold">キャンセル</button><button type="submit" className="rounded-xl bg-violet-600 px-5 py-3 text-sm font-bold text-white hover:bg-violet-700">{editing === 'new' ? form.published ? '公開する' : '保存する' : '変更を保存'}</button></div></form></FormModal>}
    <AlertDialog open={confirmSave} onOpenChange={setConfirmSave}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{form.published ? 'このお知らせを公開しますか？' : '非公開で保存しますか？'}</AlertDialogTitle><AlertDialogDescription>{form.published ? '保存後、公式サイトのお知らせ一覧へ表示されます。' : '管理画面にのみ保存されます。'}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>キャンセル</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={() => void save()}>{busy ? '保存中...' : '保存する'}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
    <AlertDialog open={Boolean(deleting)} onOpenChange={(open) => !open && setDeleting(null)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>「{deleting?.title}」を削除しますか？</AlertDialogTitle><AlertDialogDescription>この操作は取り消せません。公開中の場合は公式サイトからも削除されます。</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>キャンセル</AlertDialogCancel><AlertDialogAction className="bg-rose-600 hover:bg-rose-700" disabled={busy} onClick={() => void remove()}>削除する</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
    {toast && <Toast message={toast.text} kind={toast.kind} onClose={() => setToast(null)} />}
  </main>;
}
