'use client';

import { Pencil, Plus, Trash2, UserRound } from 'lucide-react';
import { useState } from 'react';
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from '@/components/ui/alert-dialog';
import { CastRecord, FormModal, ImageUpload, LoadingState, mutateAdmin, PageHeading, Toast, useAdminData } from '@/components/admin-common';

const empty: Omit<CastRecord, 'id' | 'isPickup' | 'pickupOrder'> = { name: '', category: '1期生', role: 'CAST', imageUrl: '', xUrl: '', favorite: '', message: '' };
const categories = ['1期生', '2期生 花組', '2期生 月組', 'スタッフ'];

export function CastManager() {
  const { data, error, reload } = useAdminData(); const [editing, setEditing] = useState<CastRecord | 'new' | null>(null); const [form, setForm] = useState(empty); const [confirmSave, setConfirmSave] = useState(false); const [deleting, setDeleting] = useState<CastRecord | null>(null); const [toast, setToast] = useState<{ text: string; kind: 'success' | 'error' } | null>(null); const [busy, setBusy] = useState(false);
  const openNew = () => { setForm(empty); setEditing('new'); };
  const openEdit = (cast: CastRecord) => { setForm({ name: cast.name, category: cast.category, role: cast.role, imageUrl: cast.imageUrl, xUrl: cast.xUrl, favorite: cast.favorite, message: cast.message }); setEditing(cast); };
  const update = (key: keyof typeof form, value: string) => setForm((current) => ({ ...current, [key]: value }));
  const save = async () => { setBusy(true); try { const result = await mutateAdmin(editing === 'new' ? { action: 'cast:create', data: form } : { action: 'cast:update', id: editing?.id, data: form }); setToast({ text: result.message || '保存しました。', kind: 'success' }); setEditing(null); await reload(); } catch (e) { setToast({ text: e instanceof Error ? e.message : '保存に失敗しました。', kind: 'error' }); } finally { setBusy(false); setConfirmSave(false); } };
  const remove = async () => { if (!deleting) return; setBusy(true); try { const result = await mutateAdmin({ action: 'cast:delete', id: deleting.id }); setToast({ text: result.message || '削除しました。', kind: 'success' }); setDeleting(null); await reload(); } catch (e) { setToast({ text: e instanceof Error ? e.message : '削除に失敗しました。', kind: 'error' }); } finally { setBusy(false); } };
  return <main><PageHeading eyebrow="Cast / Staff" title="キャスト・スタッフ管理" note="登録メンバーの追加・編集・削除を行います。" action={<button onClick={openNew} className="inline-flex h-11 items-center justify-center gap-2 rounded-xl bg-violet-600 px-4 text-sm font-bold text-white shadow-sm hover:bg-violet-700"><Plus size={17} /> 新規メンバー追加</button>} />
    {!data ? <LoadingState /> : <div className="admin-card mt-8 overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[820px] text-left"><thead className="border-b border-slate-200 bg-slate-50 text-xs text-slate-500"><tr><th className="px-5 py-4 font-semibold">プロフィール</th><th className="px-4 py-4 font-semibold">所属</th><th className="px-4 py-4 font-semibold">役職</th><th className="px-4 py-4 font-semibold">PICK UP</th><th className="px-5 py-4 text-right font-semibold">操作</th></tr></thead><tbody className="divide-y divide-slate-100">{data.casts.map((cast) => <tr key={cast.id} className="hover:bg-slate-50/70"><td className="px-5 py-4"><div className="flex items-center gap-3"><div className="grid size-11 place-items-center overflow-hidden rounded-xl bg-slate-100">{cast.imageUrl ? <img src={cast.imageUrl} alt="" className="h-full w-full object-cover" /> : <UserRound size={18} className="text-slate-400" />}</div><div><p className="font-semibold">{cast.name}</p><p className="mt-0.5 max-w-[260px] truncate text-xs text-slate-400">{cast.message || '一言未登録'}</p></div></div></td><td className="px-4 py-4 text-sm text-slate-600">{cast.category}</td><td className="px-4 py-4"><span className="rounded-lg bg-slate-100 px-2.5 py-1 text-xs font-semibold text-slate-600">{cast.role}</span></td><td className="px-4 py-4">{cast.isPickup ? <span className="rounded-full bg-amber-50 px-2.5 py-1 text-xs font-bold text-amber-700">PICK UP</span> : <span className="text-xs text-slate-300">—</span>}</td><td className="px-5 py-4"><div className="flex justify-end gap-2"><button onClick={() => openEdit(cast)} className="inline-flex items-center gap-1 rounded-lg border border-slate-200 px-3 py-2 text-xs font-semibold text-slate-600 hover:bg-slate-50"><Pencil size={14} /> 編集</button><button onClick={() => setDeleting(cast)} className="inline-flex items-center gap-1 rounded-lg border border-rose-200 px-3 py-2 text-xs font-semibold text-rose-600 hover:bg-rose-50"><Trash2 size={14} /> 削除</button></div></td></tr>)}</tbody></table></div></div>}
    {error && <p className="mt-4 text-sm text-rose-600">{error}</p>}
    {editing && <FormModal title={editing === 'new' ? '新規メンバー追加' : `${editing.name}さんを編集`} onClose={() => setEditing(null)}><form onSubmit={(e) => { e.preventDefault(); setConfirmSave(true); }} className="space-y-6 p-5 sm:p-7"><ImageUpload value={form.imageUrl} onChange={(url) => update('imageUrl', url)} label="プロフィール画像" /><div className="grid gap-5 sm:grid-cols-2"><label><span className="field-label">名前 *</span><input className="admin-input" required value={form.name} onChange={(e) => update('name', e.target.value)} /></label><label><span className="field-label">所属 *</span><select className="admin-input" value={form.category} onChange={(e) => update('category', e.target.value)}>{categories.map((item) => <option key={item}>{item}</option>)}</select></label><label><span className="field-label">役職</span><input className="admin-input" value={form.role} onChange={(e) => update('role', e.target.value)} /></label><label><span className="field-label">XプロフィールURL</span><input className="admin-input" type="url" placeholder="https://x.com/..." value={form.xUrl} onChange={(e) => update('xUrl', e.target.value)} /></label></div><label><span className="field-label">好きな物</span><input className="admin-input" value={form.favorite} onChange={(e) => update('favorite', e.target.value)} /></label><label><span className="field-label">一言</span><textarea className="admin-input min-h-28 resize-y" value={form.message} onChange={(e) => update('message', e.target.value)} /></label><div className="flex justify-end gap-3 border-t border-slate-200 pt-5"><button type="button" onClick={() => setEditing(null)} className="rounded-xl border border-slate-300 px-5 py-3 text-sm font-semibold">キャンセル</button><button type="submit" className="rounded-xl bg-violet-600 px-5 py-3 text-sm font-bold text-white hover:bg-violet-700">{editing === 'new' ? '登録する' : '変更を保存'}</button></div></form></FormModal>}
    <AlertDialog open={confirmSave} onOpenChange={setConfirmSave}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{editing === 'new' ? 'このメンバーを登録しますか？' : '変更内容を保存しますか？'}</AlertDialogTitle><AlertDialogDescription>保存後、公式サイトの表示データにも反映されます。</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>キャンセル</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={() => void save()}>{busy ? '保存中...' : editing === 'new' ? '登録する' : '保存する'}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
    <AlertDialog open={Boolean(deleting)} onOpenChange={(open) => !open && setDeleting(null)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{deleting?.name}さんを削除しますか？</AlertDialogTitle><AlertDialogDescription>この操作は取り消せません。公式サイトのキャスト一覧からも削除されます。</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>キャンセル</AlertDialogCancel><AlertDialogAction className="bg-rose-600 hover:bg-rose-700" disabled={busy} onClick={() => void remove()}>削除する</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
    {toast && <Toast message={toast.text} kind={toast.kind} onClose={() => setToast(null)} />}
  </main>;
}
