'use client';

import { ArrowDown, ArrowUp, Check, GripVertical, Star, UserRound } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { LoadingState, mutateAdmin, PageHeading, Toast, useAdminData } from '@/components/admin-common';

export function PickupManager() {
  const { data, error, reload } = useAdminData(); const initial = useMemo(() => data?.casts.filter((cast) => cast.isPickup).sort((a, b) => (a.pickupOrder ?? 99) - (b.pickupOrder ?? 99)).map((cast) => cast.id) ?? [], [data]); const [selected, setSelected] = useState<string[]>([]); const [dirty, setDirty] = useState(false); const [toast, setToast] = useState<{ text: string; kind: 'success' | 'error' } | null>(null); const [busy, setBusy] = useState(false);
  useEffect(() => { setSelected(initial); setDirty(false); }, [initial]);
  useEffect(() => { const warn = (event: BeforeUnloadEvent) => { if (dirty) event.preventDefault(); }; window.addEventListener('beforeunload', warn); return () => window.removeEventListener('beforeunload', warn); }, [dirty]);
  const toggle = (id: string) => { if (selected.includes(id)) { setSelected((current) => current.filter((item) => item !== id)); setDirty(true); return; } if (selected.length >= 8) { setToast({ text: 'PICK UPに登録できるのは最大8名です。', kind: 'error' }); return; } setSelected((current) => [...current, id]); setDirty(true); };
  const move = (index: number, direction: number) => { const next = [...selected]; const target = index + direction; if (target < 0 || target >= next.length) return; [next[index], next[target]] = [next[target], next[index]]; setSelected(next); setDirty(true); };
  const save = async () => { setBusy(true); try { const result = await mutateAdmin({ action: 'pickup:update', ids: selected }); setToast({ text: result.message || 'PICK UPを変更しました。', kind: 'success' }); setDirty(false); await reload(); } catch (e) { setToast({ text: e instanceof Error ? e.message : '保存に失敗しました。', kind: 'error' }); } finally { setBusy(false); } };
  return <main><PageHeading eyebrow="PICK UP" title="PICK UP管理" note="ホーム画面に表示するキャストを最大8名まで選択し、表示順を設定します。" action={<button onClick={() => void save()} disabled={!dirty || busy} className="inline-flex h-11 items-center justify-center gap-2 rounded-xl bg-violet-600 px-5 text-sm font-bold text-white disabled:cursor-not-allowed disabled:opacity-40"><Check size={17} /> {busy ? '保存中...' : '変更を保存'}</button>} />
    {!data ? <LoadingState /> : <div className="mt-8 grid gap-5 xl:grid-cols-[1fr_390px]"><section className="admin-card p-5 sm:p-6"><div className="flex items-center justify-between"><div><h2 className="font-bold">キャストを選択</h2><p className="mt-1 text-xs text-slate-400">カードをクリックしてPICK UPを切り替えます。</p></div><span className={`rounded-full px-3 py-1 text-sm font-bold ${selected.length === 8 ? 'bg-amber-50 text-amber-700' : 'bg-violet-50 text-violet-700'}`}>{selected.length} / 8</span></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{data.casts.filter((cast) => cast.category !== 'スタッフ').map((cast) => { const active = selected.includes(cast.id); return <button key={cast.id} onClick={() => toggle(cast.id)} className={`relative flex items-center gap-3 rounded-xl border p-3 text-left transition ${active ? 'border-violet-400 bg-violet-50 ring-2 ring-violet-100' : 'border-slate-200 hover:border-violet-200'}`}><div className="grid size-11 place-items-center overflow-hidden rounded-xl bg-slate-100">{cast.imageUrl ? <img src={cast.imageUrl} alt="" className="h-full w-full object-cover" /> : <UserRound size={17} className="text-slate-400" />}</div><div><p className="text-sm font-bold">{cast.name}</p><p className="mt-0.5 text-[11px] text-slate-400">{cast.category}</p></div>{active && <span className="absolute right-2 top-2 grid size-5 place-items-center rounded-full bg-violet-600 text-white"><Check size={12} /></span>}</button>; })}</div></section><aside className="admin-card p-5 sm:p-6"><div className="flex items-center gap-2"><Star size={18} className="text-amber-500" /><h2 className="font-bold">表示順</h2></div><p className="mt-1 text-xs text-slate-400">上から順に公式サイトへ表示されます。</p><div className="mt-5 space-y-2">{selected.map((id, index) => { const cast = data.casts.find((item) => item.id === id); if (!cast) return null; return <div key={id} className="flex items-center gap-3 rounded-xl border border-slate-200 bg-white p-3"><GripVertical size={16} className="text-slate-300" /><span className="grid size-7 place-items-center rounded-lg bg-violet-50 text-xs font-bold text-violet-700">{index + 1}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">{cast.name}</p><p className="truncate text-[10px] text-slate-400">{cast.category}</p></div><div className="flex gap-1"><button onClick={() => move(index, -1)} disabled={index === 0} className="grid size-7 place-items-center rounded-lg border border-slate-200 disabled:opacity-25" aria-label="上へ"><ArrowUp size={13} /></button><button onClick={() => move(index, 1)} disabled={index === selected.length - 1} className="grid size-7 place-items-center rounded-lg border border-slate-200 disabled:opacity-25" aria-label="下へ"><ArrowDown size={13} /></button></div></div>; })}{selected.length === 0 && <div className="rounded-xl border border-dashed border-slate-300 py-12 text-center text-sm text-slate-400">キャストを選択してください</div>}</div></aside></div>}
    {error && <p className="mt-4 text-sm text-rose-600">{error}</p>}{toast && <Toast message={toast.text} kind={toast.kind} onClose={() => setToast(null)} />}
  </main>;
}
